"""Server-authoritative pricing (ADR-0003, research R5).

Mirrors frontend/src/lib/pricing.ts function-for-function so displayed and charged prices always
agree; parity is proven in tests/unit/test_pricing_parity.py against a golden fixture generated by
frontend/scripts/export-backend-data.ts from the real frontend code. All money is integer rupees,
never a float, and every cart re-price at order time uses only this module (never a client-sent
price).
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime

from app.core import clock
from app.core.errors import AppError


@dataclass(frozen=True)
class PriceOption:
    key: str
    price_delta: int


@dataclass(frozen=True)
class PriceAddon:
    key: str
    price: int


@dataclass(frozen=True)
class PricedItem:
    """An item's own price plus its options and add-ons, with per-item overrides already applied
    (mirrors the frontend's resolved `MenuItemView`)."""

    slug: str
    base_price: int
    options: tuple[PriceOption, ...]
    addons: tuple[PriceAddon, ...]

    def option(self, key: str) -> PriceOption | None:
        return next((o for o in self.options if o.key == key), None)

    def addon(self, key: str) -> PriceAddon | None:
        return next((a for a in self.addons if a.key == key), None)


@dataclass(frozen=True)
class WeekdayPromo:
    """A weekday percentage deal (e.g. Wings Wednesday), evaluated on the Pakistan wall clock."""

    item_slug: str
    weekday: int  # 0 = Sunday ... 6, matching clock.pkt_weekday
    percent: int


def unit_price(item: PricedItem, option_key: str | None, addon_keys: Sequence[str]) -> int:
    """Base + chosen option + add-ons, in integer rupees. `option_key` may be None before the
    customer has picked (shows the base price). Raises INVALID_OPTION for an option or add-on the
    item does not offer."""
    price = item.base_price
    if option_key is not None:
        option = item.option(option_key)
        if option is None:
            raise AppError("INVALID_OPTION", f'"{item.slug}" has no option "{option_key}".')
        price += option.price_delta
    for key in addon_keys:
        addon = item.addon(key)
        if addon is None:
            raise AppError("INVALID_OPTION", f'"{item.slug}" has no add-on "{key}".')
        price += addon.price
    return price


def line_total(unit: int, quantity: int) -> int:
    return unit * quantity


def active_promo_for(item_slug: str, promos: Sequence[WeekdayPromo], now: datetime) -> WeekdayPromo | None:
    """The weekday promo running for this item right now, if any (Pakistan time)."""
    weekday = clock.pkt_weekday(now)
    return next((p for p in promos if p.item_slug == item_slug and p.weekday == weekday), None)


def promo_discount_per_unit(unit: int, promo: WeekdayPromo | None) -> int:
    """Discount per unit, rounded HALF-UP to the nearest rupee. Python's built-in `round()` rounds
    half-to-even, which disagrees with JavaScript's `Math.round` on an exact .5 rupee case, so the
    rounding is done with integer arithmetic instead."""
    if promo is None:
        return 0
    return (unit * promo.percent + 50) // 100


@dataclass(frozen=True)
class CartLineInput:
    item_slug: str
    option_key: str
    addon_keys: tuple[str, ...]
    quantity: int


@dataclass(frozen=True)
class ResolvedLine:
    line: CartLineInput
    unit_price: int
    discount_per_unit: int
    promo: WeekdayPromo | None
    line_total: int


@dataclass(frozen=True)
class ResolvedCart:
    lines: tuple[ResolvedLine, ...]
    """Lines whose item, option or add-on no longer exists on the menu."""
    invalid: tuple[CartLineInput, ...]


def resolve_cart(
    lines: Sequence[CartLineInput],
    items_by_slug: Mapping[str, PricedItem],
    promos: Sequence[WeekdayPromo],
    now: datetime,
) -> ResolvedCart:
    """Joins cart lines with the live menu and today's promos. Prices always come from the menu."""
    resolved: list[ResolvedLine] = []
    invalid: list[CartLineInput] = []
    for line in lines:
        item = items_by_slug.get(line.item_slug)
        if item is None or item.option(line.option_key) is None or any(item.addon(k) is None for k in line.addon_keys):
            invalid.append(line)
            continue
        unit = unit_price(item, line.option_key, line.addon_keys)
        promo = active_promo_for(item.slug, promos, now)
        discount = promo_discount_per_unit(unit, promo)
        resolved.append(
            ResolvedLine(
                line=line,
                unit_price=unit,
                discount_per_unit=discount,
                promo=promo,
                line_total=line_total(unit - discount, line.quantity),
            )
        )
    return ResolvedCart(lines=tuple(resolved), invalid=tuple(invalid))


@dataclass(frozen=True)
class CartTotals:
    subtotal: int
    discount: int
    delivery: int
    total: int


def cart_totals(lines: Sequence[ResolvedLine], delivery_fee: int, free_delivery_threshold: int) -> CartTotals:
    """Subtotal before deals, the deal discount, the delivery fee (free once the amount after
    discount reaches the threshold) and the total."""
    subtotal = sum(resolved.unit_price * resolved.line.quantity for resolved in lines)
    discount = sum(resolved.discount_per_unit * resolved.line.quantity for resolved in lines)
    after_discount = subtotal - discount
    delivery = 0 if len(lines) == 0 or after_discount >= free_delivery_threshold else delivery_fee
    return CartTotals(subtotal=subtotal, discount=discount, delivery=delivery, total=after_discount + delivery)
